<?php require("modules/header.php"); ?>

<div id="contents" class="clearfix">

    <div id="main">

        <div class="section">
            <div class="title"><h2>Awards</h2></div>
            <div class="text">
                <ol>
                    <li><a href="http://www.iaria.org/conferences2012/AwardsICIW12.html"><strong>ICIW2012 Best Papers Award</strong></a><br/>Yuka Koike and <span class="name">Shuichi Kurabayashi</span>, <a href="http://www.thinkmind.org/index.php?view=article&articleid=iciw_2012_10_50_20130">"Query-by-Appearance System for Style-Oriented Media Retrieval,"</a> In Proceedings of the Seventh International Conference on Internet and Web Applications and Services (<a href="http://www.iaria.org/conferences2012/ICIW12.html">ICIW 2012</a>), pp.290-295, Stuttgart, Germany, May 27 - June 1, 2012.</li>
                    <li><a href="http://www.iaria.org/conferences2012/AwardsICIW12.html"><strong>ICIW2012 Best Papers Award</strong></a><br/>Ryo Shimaoka and <span class="name">Shuichi Kurabayashi</span>, <a href="http://www.thinkmind.org/index.php?view=article&articleid=iciw_2012_6_30_20061">"Cross-Domain Query Navigation System on Tablet Devices for Search Stories of Social Groups,"</a> In Proceedings of the Seventh International Conference on Internet and Web Applications and Services (<a href="http://www.iaria.org/conferences2012/ICIW12.html">ICIW 2012</a>), pp.178-183, Stuttgart, Germany, May 27 - June 1, 2012.</li>
                    <li><a href="http://www.dasfaa.org/awards.htm"><strong>DASFAA2010 Best Demo Award</strong></a><br/><span class="name">Shuichi Kurabayashi</span> and Yasushi Kiyoki, <a href="http://www.springerlink.com/content/q34472t38t572190/">"MediaMatrix: A Video Stream Retrieval System with Mechanisms for Mining Contexts of Query Examples,"</a> In Proceedings of the 15th International Conference on Database Systems for Advanced Applications (<a href="http://dasfaa2010.cs.tsukuba.ac.jp/">DASFAA2010</a>), pp.452-455, Tsukuba, Japan, April 1-4, 2010.</li>
                </ol>
            </div>
            <div class="title"><h2>Awards for Students</h2></div>
            <div class="text">
                <ol>
                    <li><strong>[Best Student Paper Award]</strong> Nagato Kasaki, <span class="name">Shuichi Kurabayashi</span>, and Yasushi Kiyoki, "An Experience-Connected e-Learning System with a Personalization Mechanism for Learners Situations and Preferences," In Proceedings of the Industrial Electronics Seminar (IES) 2011, Surabaya, Indonesia, October 26, 2011.</li>
                    <li><strong>[学生奨励賞]</strong> 春日 優希, <span class="name">倉林 修一</span>, 清木 康, <a href="http://db-event.jpn.org/deim2010/proceedings/files/F1-4.pdf">"色彩と音楽のクロス・メディア連結機構による自動音楽生成システムの実現,"</a> 第2回データ工学と情報マネジメントに関するフォーラム (<a href="http://db-event.jpn.org/deim2010/">DEIM2010</a>),  4 pages, 2010年2月28日(日)～3月2日, 兵庫県.</li>
                    <li><strong>[学生奨励賞]</strong> 高松 耕太, <span class="name">倉林 修一</span>, 佐々木 史織, 清木 康, <a href="http://ci.nii.ac.jp/naid/110003224719">"異種領域ドキュメント群を対象にしたコンテキストの動的計量を伴う選択的情報配信機構の実現,"</a> 電子情報通信学会技術研究報告, 105(172), pp.205-210, 20050707.</li>
                </ol>
            </div>
            <div class="title"><h2>Publications</h2></div>
            <div class="text">
                <h3>Refereed Journals</h3>
                <ol>
                    <li><span class="name">Shuichi Kurabayashi</span> and Yuka Koike, <a href="http://www.iariajournals.org/internet_technology/tocv5n34.html">"Query-by-Appearance: Visual Query Expansion to Support Domain-Specific Retrieval of e-Books,"</a> International Journal on Advances in Networks and Services, ISSN:1942-2644, vol.5, no.3&amp;4, pp.162-172, IARIA, 2012.</li>
                    <li><span class="name">Shuichi Kurabayashi</span> and Ryo Shimaoka, <a href="http://www.iariajournals.org/internet_technology/tocv5n34.html">"A Cross-Domain Query Navigation and Visualization System for Touchscreens that Exploits Social Search History,"</a> International Journal on Advances in Networks and Services, ISSN:1942-2644, vol.5, no.3&amp;4, pp.186-195, IARIA, 2012.</li>
                    <li>藁谷 郁美, 太田 達也, マルコ・ラインデル, <span class="name">倉林 修一</span>, "インフォーマル・ラーニングを支援する体験連動型外国語学習環境の構築," 日本教育工学会論文誌, 36巻2号, pp.91-102, 2012.</li>
                    <li>Ana Šaša, Yasushi Kiyoki, <span class="name">Shuichi Kurabayashi</span>, Xing Chen, Marjan Krisper, <a href="http://dx.doi.org/10.3233/978-1-60750-992-9-59">"A Service-Oriented Framework for Personalized Recommender Systems Using a Colour-Impression-Based Image Retrieval and Ranking Method,"</a> Information Modelling and Knowledge Bases XXIII, IOS Press, pp.59-76, 2012.</li>
                    <li><span class="name">Shuichi Kurabayashi</span>, Shlomo Dubnov and Yasushi Kiyoki, <a href="http://dx.doi.org/10.3233/978-1-60750-477-1-258">"JoinSee: A Real-Time and Collaborative Hyper-Media System for Participatory Performances in the Opera of Meaning,"</a> Information Modelling and Knowledge Bases Vol. XXI, IOS Press, pp.258-262, 2010.</li>
                    <li><span class="name">倉林 修一</span>, 清木 康, <a href="http://www.dbsj.org/Japanese/DBSJLetters/vol5/no3/kurabayashi.pdf">"ECAルール・メタプログラミング機構を有するアクティブデータベースシステムの実現,"</a>日本データベース学会 DBSJ Letters Vol.5, No.3, pp.1-4, 2006.</li>
                    <li><span class="name">Shuichi Kurabayashi</span> and Yasushi Kiyoki, "An Active Multidatabase System Architecture with an Aspect-Oriented Media Modelling Framework," Information Modelling and Knowledge Bases Vol.XVI, IOS Press, pp.89-106, 2004.</li>
                    <li><span class="name">Shuichi Kurabayashi</span> and Yasushi Kiyoki, "A Meta-level Active Multidatabase System Architecture for Heterogeneous Information Resources," Information Modelling and Knowledge Bases Vol.XV, IOS Press, pp.143-160, 2003.</li>
                </ol>
                <h3>Refereed International Confferences</h3>
                <ol>
                    <li><span class="name">Shuichi Kurabayashi</span> and Yasushi Kiyoki, <a href="http://dx.doi.org/10.1007/978-3-642-32597-7_15">"Impression-Aware Video Stream Retrieval System with Temporal Color-Sentiment Analysis and Visualization,"</a> In Proceedings of the 23rd International Conference on Database and Expert Systems Applications (<a href="http://www.dexa.org/dexa2012">DEXA 2012</a>), pp.168-182, Vienna, Austria, September 3 - 7, 2012.</li>
                    <li>Nagato Kasaki, <span class="name">Shuichi Kurabayashi</span>, Yasushi Kiyoki, <a href="http://dx.doi.org/10.1016/j.procs.2012.06.076">"A Geo-Location Context-Aware Mobile Learning System with Adaptive Correlation Computing Methods,"</a> In Proceedings of the 9th International Conference on Mobile Web Information Systems (<a href="http://www.mobiwis.org/2012/">MobiWIS 2012</a>), pp.593-600, Niagara Falls, Ontario, Canada, August 27-29, 2012.</li>
                    <li>Mariko Komatsu, <span class="name">Shuichi Kurabayashi</span>, Yasushi Kiyoki, <a href="http://dx.doi.org/10.2316/P.2012.774-007">"A Searching Image based Knowledge Memory System by using Colors,"</a> In Proceedings of the 15th IASTED International Conference on Computers and Advanced Technology in Education (CATE 2012), pp.43-48, Napoli, Italy, June 25 – 27, 2012.</li>
                    <li>Pekka Sillberg, <span class="name">Shuichi Kurabayashi</span>, Petri Rantanen, and Naofumi Yoshida, "A Model of Evaluation: Computational Performance and Usability Benchmarks on Video Stream Context Analysis," In Proceedings of the 22nd European-Japanese Conference on Information Modelling and Knowledge Bases (<a href="http://www.ksi.mff.cuni.cz/ejc/">EJC2012</a>), pp.211-223, Prague, Czech Republic, June 4 - 9, 2012.</li>
                    <li><strong>[Best Papers Award]</strong> Yuka Koike and <span class="name">Shuichi Kurabayashi</span>, <a href="http://www.thinkmind.org/index.php?view=article&articleid=iciw_2012_10_50_20130">"Query-by-Appearance System for Style-Oriented Media Retrieval,"</a> In Proceedings of the Seventh International Conference on Internet and Web Applications and Services (<a href="http://www.iaria.org/conferences2012/ICIW12.html">ICIW 2012</a>), pp.290-295, Stuttgart, Germany, May 27 - June 1, 2012.</li>
                    <li><strong>[Best Papers Award]</strong> Ryo Shimaoka and <span class="name">Shuichi Kurabayashi</span>, <a href="http://www.thinkmind.org/index.php?view=article&articleid=iciw_2012_6_30_20061">"Cross-Domain Query Navigation System on Tablet Devices for Search Stories of Social Groups,"</a> In Proceedings of the Seventh International Conference on Internet and Web Applications and Services (<a href="http://www.iaria.org/conferences2012/ICIW12.html">ICIW 2012</a>), pp.178-183, Stuttgart, Germany, May 27 - June 1, 2012.</li>
                    <li>Riho Nakano and <span class="name">Shuichi Kurabayashi</span>, <a href="http://www.thinkmind.org/index.php?view=article&articleid=iciw_2012_10_40_20128">"A Stream-Oriented Community Generation for Integrating TV and Social Network Services,"</a> In Proceedings of the Seventh International Conference on Internet and Web Applications and Services (<a href="http://www.iaria.org/conferences2012/ICIW12.html">ICIW 2012</a>), pp.286-289, Stuttgart, Germany, May 27 - June 1, 2012.</li>
                    <li>Aya Ichinose, <span class="name">Shuichi Kurabayashi</span>, and Yasushi Kiyoki, <a href="http://dx.doi.org/10.2316/P.2011.754-041">"A Context-Based Emotion-Analyzer for Teaching Tonality in Music Courses,"</a> In Proceedings of the IASTED International Symposium on Technology for Education, pp.37-45, December 14 – 16, Dallas, USA, 2011.</li>
                    <li><strong>[Best Student Paper Award]</strong> Nagato Kasaki, <span class="name">Shuichi Kurabayashi</span>, and Yasushi Kiyoki, <a href="http://repo.eepis-its.edu/1492/">"An Experience-Connected e-Learning System with a Personalization Mechanism for Learners Situations and Preferences,"</a> In IES 2011-Emerging Technology for Better Human Life, pp.118-123, EEPIS-Surabaya, Indonesia, October 26, 2011.</li>
                    <li>Ana Šaša, Marjan Krisper, Yasushi Kiyoki, <span class="name">Shuichi Kurabayashi</span>, and Xing Chen, <a href="http://www.thinkmind.org/index.php?view=article&articleid=iciw_2011_5_20_20169">"A personalized recommender system model using a colour-impression-based image retrieval and ranking method,"</a> In Proceedings of the Sixth International Conference on Internet and Web Applications and Services (<a href="http://www.iaria.org/conferences2011/ICIW11.html">ICIW 2011</a>), pp.124-129, St. Maarten, Netherlands, March 20-25, 2011.</li>
                    <li>Haruka Fukai, Aya Ichinose, <span class="name">Shuichi Kurabayashi</span>, and Yasushi Kiyoki, <a href="http://dx.doi.org/10.2316/P.2010.725-052">"A Media-Mashup Engine with Interactive Cross-Media Association and Personalization Mechanisms,"</a> In Proceedings of the IASTED International Symposium on Software Engineering and Applications, pp.396-403, November 8-10, Marina del Rey, California, USA, 2010.</li>
                    <li>Ikumi Waragai, Tatsuya Ohta, Marco Raindl, <span class="name">Shuichi Kurabayashi</span>, Yasushi Kiyoki, Hideyuki Tokuda, "Ubiquitous language learning environments - on campus, in the city, abroad," In Proceedings of  the European Association for Computer Assisted Language Learning (EUROCALL2010), pp.231-232, 8-11 September, Bordeaux, France, 2010.</li>
                    <li>Munehiro Fukuda, Shuichi Kurabayashi, Jeremy K. Hall, and Yasushi Kiyoki, "Morphing Parallelization Strategy to Support On-the-Fly Video Analysis," In Proceedings of the 2010 International Conference on Parallel and Distributed Processing Techniques and Applications - PDPTA 2010, pp.541-547, Las Vegas, USA, July 12-15, 2010.</li>
                    <li>Jeremy Hall, <span class="name">Shuichi Kurabayashi</span>, and Yasushi Kiyoki, <a href="http://dx.doi.org/10.1109/WAINA.2010.132">"Multimedia Data Analysis on a Massively Distributed Parallelization Network of Anonymous Web Clients,"</a> The 2010 IEEE International Symposium on Mining and Web (<a href="http://www.ece.uvic.ca/~kinli/MAW10/">MAW10</a>), pp.615-620, Perth, Australia, April 20-23, 2010.</li>
                    <li><strong>[Best Demo Award]</strong> <span class="name">Shuichi Kurabayashi</span> and Yasushi Kiyoki, <a href="http://www.springerlink.com/content/q34472t38t572190/">"MediaMatrix: A Video Stream Retrieval System with Mechanisms for Mining Contexts of Query Examples,"</a> In Proceedings of the 15th International Conference on Database Systems for Advanced Applications (<a href="http://dasfaa2010.cs.tsukuba.ac.jp/">DASFAA2010</a>), pp.452-455, Tsukuba, Japan, April 1-4, 2010.</li>
                    <li><span class="name">Shuichi Kurabayashi</span>, Taichi Ueno, and Yasushi Kiyoki, <a href="http://dx.doi.org/10.1109/ISM.2009.85">"A Context-Based Whole Video Retrieval System with Dynamic Video Stream Analysis Mechanisms,"</a> In Proceedings of  the 11th IEEE International Symposium on Multimedia (<a href="http://ism2009.eecs.uci.edu/">ISM2009</a>), pp.505-510, San Diego, California, USA, December 14-16, 2009.</li>
                    <li>Takahiro Hiruma, <span class="name">Shuichi Kurabayashi</span>, and Yasushi Kiyoki, <a href="http://www.actapress.com/Abstract.aspx?paperId=36777">"Cross-Media Association Engine for Evaluating Emotive Effects of Advertisement Video Data Streams,"</a> In Proceedings of the IASTED International Symposium on Software Engineering and Applications, pp.258-261, November 2-4, Cambridge, Massachusetts, USA, 2009.</li>
                    <li>Kosuke Takano, <span class="name">Shuichi Kurabayashi</span>, Xing Chen, and Yasushi Kiyoki, <a href="http://dx.doi.org/10.1109/PACRIM.2009.5291375">"An Adaptive Search System using Heterogeneous Document Vector Spaces,"</a> In Proceedings of the 2009 IEEE Pacific Rim Conference on Communications, Computers and Signal Processing (<a href ="http://www.ece.uvic.ca/pacrim/pacrim09/">PACRIM 2009</a>), pp.193-198, Victoria, Canada, August 23-26, 2009.</li>
                    <li><span class="name">Shuichi Kurabayashi</span> and Yasushi Kiyoki, <a href="https://www.actapress.com/PaperInfo.aspx?PaperID=34329">"A Collaborative and Evolutional Active Rule Network for Dynamic Data on the Web,"</a> In Proceedings of the IASTED International Symposium on Distributed and Intelligent Multimedia Systems, pp.443-448, Orlando, Florida, USA, November 16-18, 2008.</li>
                    <li>Sahori Imai, <span class="name">Shuichi Kurabayashi</span> and Yasushi Kiyoki, <a href="http://www.actapress.com/PaperInfo.aspx?PaperID=34331">"A Music Database System with Content Analysis and Visualization Mechanisms,"</a> In Proceedings of the IASTED International Symposium on Distributed and Intelligent Multimedia Systems, pp.455-460, Orlando, Florida, USA, November 16-18, 2008.</li>
                    <li><span class="name">Shuichi Kurabayashi</span> and Yasushi Kiyoki, <a href="http://www.actapress.com/PaperInfo.aspx?PaperID=23257">"An Adaptive Active Rule System for Automatic Service Discovery and Cooperation,"</a> In Proceedings of the 24th IASTED International Conference on Applied Informatics, pp.115-122, Innsbruck, Austria, February 13–15, 2006.</li>
                    <li>Sahori Imai, <span class="name">Shuichi Kurabayashi</span>, Asako Ijichi, and Yasushi Kiyoki, <a href="http://www.actapress.com/PaperInfo.aspx?PaperID=23262">"A Music Retrieval System Supporting Intuitive Visualization by the Color Sense of Tonality,"</a> In Proceedings of the 24th IASTED International Conference on Applied Informatics, pp.153-159, Innsbruck, Austria, February 13–15, 2006.</li>
                    <li>Nobuko Miura, <span class="name">Shuichi Kurabayashi</span>, and Yasushi Kiyoki, <a href="http://dx.doi.org/10.1109/ICDE.2005.187">"An Automatic Extraction Method of Time-Series Impression-Metadata for Color Information of Video Streams,"</a> International Special Workshop on Databases For Next Generation Researchers  in conjunction with The 21st International Conference on Data Engineering (<a href="http://icde2005.is.tsukuba.ac.jp/">ICDE 2005</a>), pp.54-57, Tokyo, Japan, April 5-8, 2005.</li>
                    <li><span class="name">Shuichi Kurabayashi</span> and Yasushi Kiyoki, <a href="http://www.springerlink.com/content/x181eq5d6n0karcf/">"Aspect-ARM: An Aspect-Oriented Active Rule System for Heterogeneous Multimedia Information,"</a> The Fifth International Conference on Web Information Systems Engineering (<a href="http://www.itee.uq.edu.au/~wise04/">WISE2004</a>), Springer-Verlag LNCS 3306, pp.659-667, Brisbane, Australia, November 22-24, 2004.</li>
                    <li><span class="name">Shuichi Kurabayashi</span>, Naoki Ishibashi, Yasushi Kiyoki, <a href="http://www.actapress.com/PaperInfo.aspx?PaperID=27152">"A Multidatabase System Architecture for Integrating Heterogeneous Databases with Meta-Level Active Rule Primitives,"</a> In Proceedings of the 20th IASTED International Conference on Applied Informatics, pp.378-387, Innsbruck, Austria, February 18-21, 2002.</li>
                </ol>
                <h3>Japanese Domestic Conferences (refereed)</h3>
                <ol>
                    <li>浦木 麻子, <span class="name">倉林 修一</span>, 清木 康, "楽曲時系列印象データの階層的粒度構造化による楽曲要約メタデータ生成方式," 第4回Webとデータベースに関するフォーラム(<a href="http://db-event.jpn.org/webdbf2011/">WebDB Forum 2011</a>), 8 pages, 2011年11月4日～5日, 東京都.</li>
                    <li>佐藤 篤, <span class="name">倉林 修一</span>, 清木 康, <a href="http://www.ieice.org/~de/DEWS/DEWS2008/proceedings/files/e4/e4-3.pdf">"コミュニティ構築型辞書グラフを用いた異種メディアデータ連結機構の実現,"</a> 電子情報通信学会 第19回データ工学ワークショップ (<a href="http://www.ieice.org/~de/DEWS/DEWS2008/">DEWS2008</a>), 8 pages, 2008年3月9日～11日, 宮崎県.</li>
                    <li>森 薫, <span class="name">倉林 修一</span>, 石橋 直樹, 清木 康, <a href="http://www.ieice.org/~de/DEWS/proc/2004/paper/1-A/1-A-04.pdf">"モバイルコンピューティング環境におけるユーザ情報の動的計量による能動型情報配信,"</a> 電子情報通信学会 第15回データ工学ワークショップ (<a href="http://www.dl.kuis.kyoto-u.ac.jp/DEWS2004/">DEWS2004</a>), 8 pages, 2004年3月4日～6日, 三重県.</li>
                </ol>
                <h3>Japanese Domestic Conferences (non-refereed)</h3>
                <ol>
                    <li>今井 樹, <span class="name">倉林 修一</span>, " Chord-Cube: 和音距離計量空間による楽曲可視化・ナビゲーションシステム," 第4回データ工学と情報マネジメントに関するフォーラム(<a href="http://db-event.jpn.org/deim2012/">DEIM2012</a>), 2012年3月3日～3月5日, 兵庫県.</li>
                    <li>矢部 竜太, <span class="name">倉林 修一</span>, 清木 康, "配信情報と利用者の関係性を動的に計量する位置情報に基づく情報配信システムの提案," 第4回データ工学と情報マネジメントに関するフォーラム(<a href="http://db-event.jpn.org/deim2012/">DEIM2012</a>), 2012年3月3日～3月5日, 兵庫県.</li>
                    <li>藁谷 郁美, 太田 達也, マルコ ラインデル, <span class="name">倉林 修一</span>, "インフォーマル・ラーニングを支援するユビキタス外国語学習環境の構築," 日本教育工学会研究報告集 JSET(11-4), pp.189-194, 2011年10月29日, 島根県.</li>
                    <li>加嵜 長門, <span class="name">倉林 修一</span>, 清木 康, <a href="http://ci.nii.ac.jp/naid/40018913197">"学習者の状況・嗜好に応じた教材配信機能を有する体験連動型マルチリンガル外国語e-Learningシステム,"</a> 教育システム情報学会研究報告, Vol.26, No.2, pp.41-48, 2011-07.</li>
                    <li><span class="name">倉林 修一</span>, 清木 康, <a href="http://ci.nii.ac.jp/naid/40018900280">"時系列色彩分析機能による動画像印象ソーシャルタギング,"</a> 電子情報通信学会技術研究報告, Vol.111, No.76, DE2011-25, PRMU2011-56 (2011-6) pp.137-142, 2011年6月6日～2011年6月7日, 神奈川県.</li>
                    <li>市瀬 綾, <span class="name">倉林 修一</span>, 清木 康, <a href="http://db-event.jpn.org/deim2011/proceedings/pdf/b7-4.pdf">"時系列印象変化抽出機構による音楽検索データベースシステムの実現,"</a> 第3回データ工学と情報マネジメントに関するフォーラム(<a href="http://db-event.jpn.org/deim2011/">DEIM2011</a>), 2011年2月27日～3月1日, 静岡県.</li>
                    <li>小池 悠佳, <span class="name">倉林 修一</span>, <a href="http://db-event.jpn.org/deim2011/proceedings/pdf/a9-4.pdf">"エディトリアル・デザインに関するテンプレートを用いたクエリ入力支援機能を有するe-Books検索エンジン,"</a> 第3回データ工学と情報マネジメントに関するフォーラム(<a href="http://db-event.jpn.org/deim2011/">DEIM2011</a>), 2011年2月27日～3月1日, 静岡県.</li>
                    <li>島岡 諒, <span class="name">倉林 修一</span>: <a href="http://db-event.jpn.org/deim2011/proceedings/pdf/f9-3.pdf">"タブレット端末を対象とした複合検索語ナビゲーション機能を有するタイピング・フリー検索機構,"</a> 第3回データ工学と情報マネジメントに関するフォーラム(<a href="http://db-event.jpn.org/deim2011/">DEIM2011</a>), 2011年2月27日～3月1日, 静岡県.</li>
                    <li>加嵜 長門, <span class="name">倉林 修一</span>, 清木 康, <a href="http://db-event.jpn.org/deim2011/proceedings/pdf/e4-1.pdf">"学習者の状況・嗜好に応じた教材配信機能を有する体験連動型マルチリンガル外国語e-Learningシステム,"</a> 第3回データ工学と情報マネジメントに関するフォーラム(<a href="http://db-event.jpn.org/deim2011/">DEIM2011</a>), 2011年2月27日～3月1日, 静岡県.</li>
                    <li>小松 万里子, <span class="name">倉林 修一</span>, 清木 康, <a href="http://db-event.jpn.org/deim2011/proceedings/pdf/e3-1.pdf">"色彩に応じたレシピ検索・共有ソーシャルコミュニティ・システム,"</a> 第3回データ工学と情報マネジメントに関するフォーラム(<a href="http://db-event.jpn.org/deim2011/">DEIM2011</a>), 2011年2月27日～3月1日, 静岡県）.</li>
                    <li>石井 千賀, <span class="name">倉林 修一</span>, 清木 康, <a href="http://db-event.jpn.org/deim2011/proceedings/pdf/e8-3.pdf">"文書印象表現単語とフォントの感性的相関量計量による動的文書装飾システム,"</a> 第3回データ工学と情報マネジメントに関するフォーラム(<a href="http://db-event.jpn.org/deim2011/">DEIM2011</a>), 2011年2月27日～3月1日, 静岡県.</li>
                    <li><span class="name">倉林 修一</span>, 清木 康, <a href="http://ci.nii.ac.jp/naid/110008139024">"動画像ストリームを対象とした内容検索・配信のためのアクティブルール記述・実行手法,"</a> 情報処理学会第72回全国大会講演論文集, "5-79"-"5-80", 2010-03-08, 東京都.</li>
                    <li><strong>[学生奨励賞]</strong> 春日 優希, <span class="name">倉林 修一</span>, 清木 康, <a href="http://db-event.jpn.org/deim2010/proceedings/files/F1-4.pdf">"色彩と音楽のクロス・メディア連結機構による自動音楽生成システムの実現,"</a> 第2回データ工学と情報マネジメントに関するフォーラム (<a href="http://db-event.jpn.org/deim2010/">DEIM2010</a>),  4 pages, 2010年2月28日(日)～3月2日, 兵庫県.</li>
                    <li>矢部 竜太, <span class="name">倉林 修一</span>, 清木 康, <a href="http://db-event.jpn.org/deim2009/proceedings/files/B3-4.pdf">"場所に応じた行動履歴解釈機能を有するユビキタスセンサ・知識ベース統合型アクティブ・マルチDBSの実現方式,"</a> 第1回データ工学と情報マネジメントに関するフォーラム (<a href="http://db-event.jpn.org/deim2009/">DEIM2009</a>), 8 pages, 2009年3月8日～10日, 静岡県.</li>
                    <li>昼間 貴宏, <span class="name">倉林 修一</span>, 清木 康, <a href="http://db-event.jpn.org/deim2009/proceedings/files/i1-38.pdf">"スポーツ映像を対象としたストリーム処理型内容分析によるスポンサー広告価値計量方式と実現,"</a> 第1回データ工学と情報マネジメントに関するフォーラム (<a href="http://db-event.jpn.org/deim2009/">DEIM2009</a>), 6 pages, 2009年3月8日～10日, 静岡県.</li>
                    <li>今井 小帆里, <span class="name">倉林 修一</span>, 清木 康, <a href="http://ci.nii.ac.jp/naid/110006980288/">"連続メディアデータ分析・可視化機構を有する音楽データベースシステムの実現方式,"</a> 情報処理学会研究報告. データベース・システム研究会報告, 2008(88)  pp.151-156, 20080914.</li>
                    <li>上野 太一, <span class="name">倉林 修一</span>, 清木 康, <a href="http://ci.nii.ac.jp/naid/110006980321">"動画像における色彩特徴量の分析による感性メタデータ自動生成および時系列メディアデータ検索機構の実現,"</a> 情報処理学会研究報告 データベース・システム研究会報告, 2008(88)  pp.349-354, 20080914.</li>
                    <li><span class="name">倉林 修一</span>, 清木 康: <a href="http://ci.nii.ac.jp/naid/110006863854">"マルチメディアデータを対象とした情報モニタリングのためのアクティブルール記述・管理手法,"</a>全国大会講演論文集 第70回平成20年(5), pp.5-13, 20080313.</li>
                    <li><strong>[学生奨励賞]</strong> 高松 耕太, <span class="name">倉林 修一</span>, 佐々木 史織, 清木 康, <a href="http://ci.nii.ac.jp/naid/110003224719">"異種領域ドキュメント群を対象にしたコンテキストの動的計量を伴う選択的情報配信機構の実現,"</a> 電子情報通信学会技術研究報告, 105(172), pp.205-210, 20050707.</li>
                    <li>三浦 伸子, <span class="name">倉林 修一</span>, 清木 康, <a href="http://www.ieice.org/~de/DEWS/DEWS2005/procs/papers/6A-i5.pdf">"映像データの色彩情報を対象とした時系列印象メタデータの生成方式,"</a> 電子情報通信学会 第16回データ工学ワークショップ (DEWS2005), 8 pages, 2005年2月28日～3月2日</li>
                    <li>苅谷 花子, <span class="name">倉林 修一</span>, 清木 康, <a href="http://ci.nii.ac.jp/naid/110003174737">"味覚印象を対象としたメタデータ生成方式と印象検索方式の実現,"</a> 電子情報通信学会技術研究報告, 104(176), pp.115-120, 20040706.</li>
                    <li><span class="name">倉林 修一</span>, 石橋 直樹, 清木 康, <a href="http://ci.nii.ac.jp/naid/110003189026/">"モバイル・コンピューティング環境におけるアクティブ型マルチデータベースの実現方式,"</a> 電子情報通信学会技術研究報告, 100(228), pp.87-94, 20000721.</li>
                </ol>
            </div>
            <div class="title"><h2>Invited Talk</h2></div>
            <div class="text">
                <ol>
                    <li><span class="name">倉林 修一</span>, "ユビキタス体験連動型ドイツ語学習環境," 京都ドイツ語学研究会第７６回例会, シンポジウム「外国語学習のあらたな地平 －慶應義塾大学SFCドイツ語教材開発研究プロジェクトの取り組み－」, 2011年12月3日, 京都大学. </li>
                </ol>
            </div>
            <div class="title"><h2>Grants (Principal Investigator)</h2></div>
            <div class="text">
                <ol>
                    <li>研究代表者: <span class="name">倉林 修一</span>, 日本学術振興会 科学研究費補助事業（学術研究助成基金助成金） (Japan Society for the Promotion of Science (JSPS), Grants-in-Aid for Scientific Research (KAKENHI)), 若手研究（Ｂ）, <a href="http://kaken.nii.ac.jp/ja/p/23700128">"Ｗｅｂ動画像・音楽メディアを対象とした感性自動分析・個人化・配信システムの実現"</a>, 課題番号：23700128, 2011-2012年度.</li>
                    <li>研究代表者: <span class="name">倉林 修一</span>, 総務省 戦略的情報通信研究開発推進制度 (Ministry of Internal Affairs and Communications (MIC), SCOPE: Strategic Information and Communications R&amp;D Promotion Programme) 若手ICT研究者育成型研究開発, <a href="http://www.soumu.go.jp/main_sosiki/joho_tsusin/scope/subject/s_h22.html">"動画像・音楽メディアを対象とした印象分析・可視化・配信のための感性時系列メディア・ハブ機構の研究開発"</a>, 2010-2012年度.</li>
                    <li>研究代表者: <span class="name">倉林 修一</span>, 文部科学省 科学研究費補助金 (Ministry of Education, Culture, Sports, Science and Technology (MEXT), Grants-in-Aid for Scientific Research (KAKENHI)) 若手研究（Ｂ）, <a href="http://kaken.nii.ac.jp/ja/p/21700117">"動画像・音楽データ対象アクティブ・感性マルチメディア配信システム環境の実現"</a>, 課題番号：21700117, 2009-2010年度.</li>
                </ol>
            </div>
            <div class="title"><h2>Grants (Co-investigator)</h2></div>
            <div class="text">
                <ol>
                    <li>研究代表者: 藁谷 郁美, 研究分担者: 徳田 英幸, 清木 康, 太田 達也, <span class="name">倉林 修一</span>, "体験連動型ユビキタス・外国語教育メディア自動配信システム国際的実利用環境構築," 日本学術振興会 科学研究費助成事業 (Japan Society for the Promotion of Science (JSPS), Grants-in-Aid for Scientific Research (KAKENHI)), 基盤研究（Ｂ）, 課題番号：24320107, 2012-2015年度.</li>
                </ol>
            </div>
            <div class="title"><h2>Granted Patents</h2></div>
            <div class="text">
                <ol>
                    <li>JP特許取得, <span class="name">倉林 修一</span>, 吉田 尚史, 鷹野 孝典, 特許第5180368号, "情報処理装置およびプログラム," 登録日：平成25年1月18日, 特願2011-505308, 出願日: 2010年10月04日, (国際出願番号: PCT/JP2010/67337, 国際公開番号: <a href="patent/WO2012046286.pdf">WO/2012/046286</a>).</li>
                    <li>US Patent, Kosuke Takano, Naofumi Yoshida, <span class="name">Shuichi Kurabayashi</span>, Patent Number: 8,327,367, <a href="patent/US8327367.pdf">"Information service providing system, information service providing device, and method therefor ,"</a> Date of Patent: December 4, 2012, Publication Date: September 22, 2011, 2011, Publication No. 20110231863, Application No. 12/665,304 (International Application: PCT/JP2009/054140, <a href="patent/WO2010100735.pdf">WO/2010/100735</a>).</li>
                    <li>US Patent, Naofumi Yoshida, Kosuke Takano, <span class="name">Shuichi Kurabayashi</span>, Patent Number: 8,218,054, <a href="patent/US8218054.pdf">"Image Display system, Image Display Apparatus, Image Providing Apparatus and Method Thereof,"</a> Date of Patent: July 10, 2012, Publication Date: May 10, 2011, Publication No.: 20110058046, Application No.: 12/665,295, Filing Date: December 17, 2009 (International Application: PCT/JP2009/055108, <a href="patent/WO2010106632.pdf">WO/2010/106632</a>).</li>
                    <li>US Patent, Naofumi Yoshida, Kosuke Takano, <span class="name">Shuichi Kurabayashi</span>, Patent Number: 8,013,866, <a href="patent/US8013866.pdf">"Image display system, image display apparatus, image providing apparatus and method thereof,"</a> Date of Patent: September 6, 2011, Publication Date: September 23, 2010, Publication No.: 20110050717, Application No. 12/665,153, Filing Date: March 17, 2009 (International Application: PCT/JP2009/055107, <a href="patent/WO2010106631.pdf">WO/2010/106631</a>).</li>
                    <li>US Patent, Kosuke Takano, Naofumi Yoshida, <span class="name">Shuichi Kurabayashi</span>, Patent Number: 7,975,284, <a href="patent/US7975284.pdf">"Image Capturing System, Image Capturing Apparatus, and Image Capturing Method,"</a> Date of Patent: July 5, 2011, Application No. 12/568,188, Filing Date: September 28, 2009 (based on JP 2009-060544).</li>
                    <li>JP特許取得, 鷹野 孝典, 吉田 尚史, 倉林 修一, 特許第5044661号, <a href="patent/JPB_0005044661.pdf">"情報サービス提供システム、情報サービス提供装置およびその方法,"</a> 登録日：平成24年7月20日, 特願2009-545026, 出願日：平成21年3月5日, (国際出願番号: PCT/JP2009/054139, 国際公開番号: <a href="patent/WO2010100734.pdf">WO/2010/100734</a>).</li>
                    <li>JP特許取得, 鷹野 孝典, 吉田 尚史, <span class="name">倉林 修一</span>, 特許第4931089号, <a href="patent/2010-217948.pdf">"健康診断システム、健康診断装置およびその方法,"</a> 登録日：平成24年2月24日, 出願日：平成21年3月13日, 特開2010-217948, 特願2009-060545.</li>
                    <li>JP特許取得, 鷹野 孝典, 吉田 尚史, <span class="name">倉林 修一</span>, 特許第4668347号, <a href="patent/JPB_0004668347.pdf">"情報サービス提供システム、情報サービス情報提供装置およびその方法,"</a> 登録日：平成23年1月21日, 出願日：平成21年3月5日, 特願2009-545027 (国際出願: PCT/JP2009/054140, 国際公開番号: <a href="patent/WO2010100735.pdf">WO/2010/100735</a>).</li>
                    <li>JP特許取得, 吉田 尚史, 鷹野 孝典, <span class="name">倉林 修一</span>, 特許第4614373号, <a href="patent/JPB_0004614373.pdf">"画像表示システム、画像表示装置、画像提供装置およびその方法,"</a> 登録日：平成22年10月29日, 出願日：平成21年3月17日, 特願2009-545025 (国際出願: PCT/JP2009/055108, 国際公開番号: <a href="patent/WO2010106632.pdf">WO/2010/106632</a>).</li>
                    <li>JP特許取得, 吉田 尚史, 鷹野 孝典, <span class="name">倉林 修一</span>, 特許第4573910号, <a href="patent/JPB_0004573910.pdf">"画像表示システム、画像表示装置、画像提供装置およびその方法,"</a> 登録日：平成22年8月27日, 出願日：平成21年3月17日,  特願2009-545030 (国際出願: PCT/JP2009/055107, 国際公開番号: <a href="patent/WO2010106631.pdf">WO/2010/106631</a>).</li>
                    <li>JP特許取得, 吉田 尚史, <span class="name">倉林 修一</span>, 鷹野 孝典, 特許第4376962号, <a href="patent/JPB_0004376962.pdf">"ナビゲーションシステム、ナビゲーション装置およびその方法,"</a>  登録日：平成21年9月18日, 出願日：平成21年3月13日, 特開2010-216815, 特願2009-060546.</li>
                    <li>JP特許取得, 鷹野 孝典, 吉田 尚史, <span class="name">倉林 修一</span>, 特許第4369526号, <a href="patent/JPB_0004369526.pdf">"画像撮影システム、画像撮影装置およびその方法,"</a> 登録日：平成21年9月4日, 出願日：平成21年3月13日, 特開2010-219593, 特願2009-060544.</li>
                </ol>
            </div>
            <div class="title"><h2>Patents In Application</h2></div>
            <div class="text">
                <ol>
                    <li>PCT Application, <span class="name">Shuichi Kurabayashi</span>, "LOAD BALANCING SCHEME," International Application: PCT/US2012/070063, Filing Date: December 17, 2012.</li>
                    <li>PCT Application, <span class="name">Shuichi Kurabayashi</span>, "DATA LIST CUSTOMIZATION BASED ON SOCIAL RELATIONSHIP," International Application: PCT/US2012/059937, Filing Date: October 12, 2012.</li>
                    <li>US Application, <span class="name">Shuichi Kurabayashi</span>, "CLOUD PROCESS MANAGEMENT," Application No. 13/809,012, Filing Date: January 8, 2013, (International Application No. PCT/US2012/051924, August 22, 2012).</li>
                    <li>PCT Application, Naofumi Yoshida, Kosuke Takano, <span class="name">Shuichi Kurabayashi</span>, "DYNAMIC CONTENT PREVIEW," International Application No. PCT/US2012/050726, Filing Date: August 14, 2012.</li>
                    <li>US Application, <span class="name">Shuichi Kurabayashi</span>, Naofumi Yoshida, Kosuke Takano, "NETWORK CONGESTION REDUCTION," Application No. 13/697,294, Filing Date: November 9, 2012, (International Application No. PCT/US2012/046189, July 11, 2012). </li>
                    <li>US Application, <span class="name">Shuichi Kurabayashi</span>, Naofumi Yoshida, Kosuke Takano, "DETECTING GAME PLAY-STYLE CONVERGENCE AND CHANGING GAMES," Application No. 13/533,774, Filing Date: June 26, 2012. </li>
                    <li>US Application, <span class="name">Shuichi Kurabayashi</span>, Naofumi Yoshida, Kosuke Takano, "MAINTENANCE-COST-AWARE BILLING FOR CLOUD SERVICES," Application No. 13/576,383, Filing Date: July 31, 2012 (International Application No. PCT/US2012/029988, March 21, 2012).</li>
                    <li>US Application, <span class="name">Shuichi Kurabayashi</span>, Naofumi Yoshida, Kosuke Takano, "LOAD BALANCING FOR GAME," Application No. 13/426,868, Filing Date: March 22, 2012.</li>
                    <li>US Application, <span class="name">Shuichi Kurabayashi</span>, Naofumi Yoshida, Kosuke Takano, "CONTEXT-BASED CONTENT LIST GENERATION," Application No. 13/642,689, Filing Date: October 22, 2012 (International Application No. PCT/US2012/026524, February 24, 2012).</li>
                    <li>US Application, <span class="name">Shuichi Kurabayashi</span>, Naofumi Yoshida, Kosuke Takano, "GEOLOCATION-BASED LOAD BALANCING," Application No. 13/640,888, Filing Date: October 20, 2012 (International Application No. PCT/US2012/026521, February 24, 2012).</li>
                    <li>PCT Application, <span class="name">Shuichi Kurabayashi</span>, Naofumi Yoshida, Kosuke Takano, "AUTOMATIC PRIVACY MANAGEMENT FOR IMAGE SHARING NETWORKS," International Application No. PCT/US2011/065575, December 16, 2011.</li>
                    <li>PCT Application, <span class="name">Shuichi Kurabayashi</span>, Naofumi Yoshida, Kosuke Takano, "CONTENT-BASED AUTOMATIC INPUT PROTOCOL SELECTION," International Application No. PCT/US2011/064453, December 12, 2011.</li>
                    <li>US Application, <span class="name">Shuichi Kurabayashi</span>, Naofumi Yoshida, Kosuke Takano, <a href="patent/USApp20120319965.pdf">"PROCESS MANAGEMENT IN A MULTI-CORE ENVIRONMENT,"</a> Publication No. 20120319965, Publication Date: December 20, 2012, Application No. 13/388,663, Filing Date: Feburary 2, 2012, (International Application No. PCT/US2011/040599, International Publication No. <a href="patent/WO2012173622.pdf">WO/2012/173622</a>).</li>
                    <li>PCT Application, <span class="name">Shuichi Kurabayashi</span>, Naofumi Yoshida, Kosuke Takano, "PEAK-PERFORMANCE-AWARE BILLING FOR CLOUD COMPUTING ENVIRONMENT," International Application No. PCT/US2011/040368, International Publication No. <a href="patent/WO2012173604.pdf">WO/2012/173604</a>.</li>
                    <li>US Application, <span class="name">Shuichi Kurabayashi</span>, Naofumi Yoshida, Kosuke Takano, <a href="patent/USApp20120143361.pdf">"AUGMENTED REALITY SYSTEM,"</a> Publication No. 20120143361, Application No. 13/139,819, Publication Date: June 7, 2012, Filing Date: June 15, 2011, (International Application No. PCT/US2010/058675, International Publication No. <a href="patent/WO2012074528.pdf">WO/2012/074528</a>). </li>
                    <li>US Application, <span class="name">Shuichi Kurabayashi</span>, Naofumi Yoshida, Kosuke Takano, <a href="patent/USApp20120084232.pdf">"FLAT RATE PRICING WITH PACKET-FREQUENCY AWARE BILLING SYSTEM FOR MOBILE BROADBAND COMMUNICATION,"</a> Publication No. 20120084232, Application No. 13/127,301, Publication Date: April 5, 2012, Filing Date: May 3, 2011, (International Application No. PCT/JP2010/67337, International Publication No. <a href="patent/WO2012046286.pdf">WO/2012/046286</a>).</li>
                    <li>US Application, <span class="name">Shuichi Kurabayashi</span>, Naofumi Yoshida, Kosuke Takano, <a href="patent/USApp20110161974.pdf">"Methods and Apparatus for Parallelizing Heterogeneous Network Communications in Smart Devices,"</a> Publication No. 20110161974, Application No. 12/647,711, Publication Date: June 30, 2011, Filing Date: December 28, 2009.</li>
                    <li>US Application, <span class="name">Shuichi Kurabayashi</span>, Naofumi Yoshida, Kosuke Takano, <a href="patent/USApp20110153278.pdf">"Sensor-Based Data Filtering Systems,"</a> Publication No. 20110153278, Application No. 12/645,385, Publication Date: June 23, 2011, Filing Date: December 22, 2009.</li>
                    <li>US Application, Kosuke Takano, Naofumi Yoshida, <span class="name">Shuichi Kurabayashi</span>, <a href="patent/USApp20110150434.pdf">"A Pan camera controlling method,"</a> Publication No. 20110150434, Application No. 12/645,837, Publication Date: June 23, 2011, Filing Date: December 23, 2009.</li>
                    <li>US Application, Kosuke Takano, Naofumi Yoshida, <span class="name">Shuichi Kurabayashi</span>, <a href="patent/USApp20100234694.pdf">"Health Check System, Health Check Apparatus and Method Thereof,"</a> Publication No. 20100234694, Application No. 12/640,967, Publication Date: September 16, 2010,  Filing Date: December 17, 2009, (based on JP 2009-060545).</li>
                    <li>US Application, Kosuke Takano, Naofumi Yoshida, <span class="name">Shuichi Kurabayashi</span>, <a href="patent/USApp20110191056.pdf">"Information Service Providing System, Information Service Providing Device, and Method Therefor,"</a> Publication No. 20110191056, Application No. 12/665,107, Publication Date: August 4, 2011, (International Application No. PCT/JP2009/054139, International Publication No. <a href="patent/WO2010100734.pdf">WO/2010/100734</a>).</li>
                    <li>JP出願, 清木 康, 陳 幸生, <span class="name">倉林 修一</span>, <a href="patent/JPA_2012221400.pdf">"デザイン生成装置及びデザイン生成プログラム,"</a> 特願2011-089059, 出願日: 平成23年4月13日, 特開2012-221400, 公開日：平成24年11月12日.</li>
                    <li>JP出願, 角田 史記, 斎藤 武, 清木 康, <span class="name">倉林 修一</span>, <a href="patent/JPA_2012108654.pdf">"コンテンツ選択装置、コンテンツ選択方法,"</a> 特願2010-255933, 出願日: 平成22年11月16日, 特開2012-108654, 公開日: 平成24年6月7日.</li>
                </ol>
            </div>

            <br />
            <a href="index.html">トップページへ戻る</a>
        </div>


        <!-- / #main --></div>

    <?php require("modules/sub.php"); ?>

    <!-- / #contents --></div>

<?php require("modules/footer.php"); ?>